language: node_js
  node_js:
  - "11"
sudo: required
before_stall:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
after_script:
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: app-academico
